### ISSUE TITLE
script to compile signatures and custom signatures by ext. account

### ISSUE THREAD

**Issue by timberbee** [EvidentSecurity/automation#12]
### ESP Automation Request
would like a script that allows them to see signatures and custom signatures by account. They often set the risk level for the same signature differently for different exteranl accounts. 
---

#### Request (Select one):

- [x] Automation Script
- [ ] Auto-Remediation Function

#### Type (Select one):

- [x] New Project
- [ ] Feature Enhancement
- [ ] Bug Report

#### Priority:

- [x ] High
- [] Medium
- [ ] Low
 
 
#### Cloud Provider:

- [x] AWS
- [ ] Azure

#### Description:

[ If the current behavior is a bug, please provide the steps to reproduce. ]

#### Use Case:

[ What is the expected behavior? ]
A report will be generated (csv), that lists the signature identifier and description and its risk level, grouped by external account for an organization
#### Technical Requirements:

[ Provide details. ]

#### Supporting Image / Examples:

```
Code examples, error output, etc.
```

#### Additional Comments:

[ The customer would like XYZ... ]
I have set this to high as this has been an outstanding request by Vanguard since January 4th. My fault that this is the first time Ive opened a ticket for this.

**Comment by hutch34** [comment]
@timberbee Hey Tim, this should be doable with the following script: https://github.com/EvidentSecurity/automation/blob/master/risk_levels_audit.py
