### ISSUE TITLE
Script to download audit data for automated ingestion into Splunk

### ISSUE THREAD

**Issue by gadouryd** [EvidentSecurity/automation#2]
### ESP Automation Request

---

#### Request (Select one):

- [x] Automation Script
- [ ] Auto-Remediation Function

#### Type (Select one):

- [x] New Project
- [ ] Feature Enhancement
- [ ] Bug Report

#### Priority:

- [ ] High
- [x] Medium
- [ ] Low
 
 
#### Cloud Provider:

- [x] AWS
- [ ] Azure

#### Description:

Customer needs to stream audit logs into Splunk (Sumo, ELK) but that feature is not yet in ESP. Until that is done they need a way to automate sending the data to Splunk

#### Use Case:

The script will download all audit logs for the previous day and write them to a file where they can then be automatically ingested. The customer can setup a cron job to do this.

An added bonus would be for a custom time range to query

#### Technical Requirements:

Query for previous days audit logs and write them to a file (csv) in a single diredctory
Documentation should include a note for customers to setup file management to clear out old files

#### Supporting Image / Examples:

```
Code examples, error output, etc.
```

**Comment by toddm92** [comment]
#### New script:
* audit_logs_dump.py

#### Description:
This script dumps an ESP audit report to a csv formatted file called, "esp_audit_report_YYYYMMDDTHHMMSS.csv" in the same directory that the script is executed in.

#### Options:
* Grab your ESP API credentials from the OS environment:
pub_key = os.environ["ESP_ACCESS_KEY_ID"]
secret_key = os.environ["ESP_SECRET_ACCESS_KEY"]

* Or, include your keys in the script (might be easier if executing the script from cron):
pub_key = <your_esp_access_key_id>
secret_key = <your_esp_secret_access_key>

---

* Set the number of log entries to search and report on.
*example1:*
no_of_pages = 5     # search 250 log enteries
no_of_days  = 1       # return the last 24 hrs of activity
*example2:*
no_of_pages = 10    # search 500 log enteries
no_of_days  = 3       # return the last 3 days of activity

Note: Wish list -> ```audit_logs``` API support for the ```filter[created_at_lt]``` filter/ predicate.

#### Usage:
````
python audit_logs_dump.py 
Success: Created ESP csv audit report, esp_audit_report_20170801T070252.csv.
````

To execute from cron once a day at 11:50pm:
```
chmod +x audit_logs_dump.py
```
```
50 23 * * * /<location_of_the_script>/audit_logs_dump.py
```

#### File format:
```
id,platform,created_at,organization_id,organization_name,user_email,user_ip,access_denied,successful,action,item_type,item_id
185227,UI,2017-08-01T13:37:48.000Z,14,Demo Inc.,demo@evident.io,10.10.10.1,False,True,update,Integration::AmazonSns,195
184983,UI,2017-08-01T12:18:49.000Z,14,Demo Inc.,demo@evident.io,10.10.10.2,False,True,create,APIKey,502
184982,UI,2017-08-01T12:18:34.000Z,14,Demo Inc.,demo@evident.io,10.10.10.3,False,True,destroy,APIKey,390
...
```

**Comment by toddm92** [comment]
@gadouryd Test it out.. lemme know how it goes, or if you'd like to see any modifications.

**Comment by toddm92** [comment]
Closing...
