### ISSUE TITLE
Script to create users in ESP

### ISSUE THREAD

**Issue by gadouryd** [EvidentSecurity/automation#3]
### ESP Automation Request

---

#### Request (Select one):

- [x] Automation Script
- [ ] Auto-Remediation Function

#### Type (Select one):

- [x] New Project
- [ ] Feature Enhancement
- [ ] Bug Report

#### Priority:

- [x ] High
- [] Medium
- [ ] Low
 
 
#### Cloud Provider:

- [x] AWS
- [ ] Azure

#### Description:

Customer is looking for a script to automate creating users in ESP. 

#### Use Case:

Automatically create new users and assign roles in ESP.

#### Technical Requirements:

Read from a list of user names, email addresses, roles to create user accounts in ESP

#### Supporting Image / Examples:

```
Code examples, error output, etc.
```

**Comment by toddm92** [comment]
Two scripts:

* create_esp_users.py
* users_audit.py

The first script reads from a csv file containing a list of ESP users and attempts to create each one. It looks for a file called "esp_users.csv" is the same directory the script is executed in.

Here's the file format:
```
First Name,Last Name,Email,Role
Jimmy,Page,jimmy@rock.io,customer
Randy,Rhodes,randy@rock.io,manager
Eric,Clapton,eric@rock.io,manager
```
The first 3 fields are required; **first name**, **last name** and **email**.  If the role field is left blank i.e. ``` Eric,Clapton,eric@rock.io, ``` the default role is "manager." 

Sample usage & output:
```
./create_esp_users.py 
Created ESP user -> jimmy@rock.io
Created ESP user -> randy@rock.io
Created ESP user -> eric@rock.io
```

---

The second script dumps a list of ESP users for an organization to a csv file called, "esp_users_report.csv" in the same directory that the script is executed in.  Alternatively, you can simply list ESP users in json format to the screen.

Here's the usage:
```
usage: users_audit.py [-h] -o <output>

Output option.

optional arguments:
  -h, --help   show this help message and exit
  -o <output>  csv or json
```

Sample output:
```
[
    {
        "First Name": "Eric",
        "Last Name": "Clapton",
        "Email": "eric@rock.io",
        "Role": "manager",
        "Organization": "Demo Inc.",
        "Last Updated": "Jul 17, 2017 04:15:34 PM",
        "MFA Enabled": false
    },
    {
        "First Name": "Randy",
        "Last Name": "Rhodes",
        "Email": "randy@rock.io",
        "Role": "manager",
        "Organization": "Demo Inc.",
        "Last Updated": "Jul 17, 2017 04:15:33 PM",
        "MFA Enabled": false
    },
    {
        "First Name": "Jimmy",
        "Last Name": "Page",
        "Email": "jimmy@rock.io",
        "Role": "customer",
        "Organization": "Demo Inc.",
        "Last Updated": "Jul 17, 2017 04:15:33 PM",
        "MFA Enabled": false
    },
...
```

**Comment by toddm92** [comment]
Added support for the addition of ESP Teams.

File format (Role & Teams are both optional):
```
First Name,Last Name,Email,Role,Teams
Jimmy,Page,jimmy@rock.io,customer,TeamA,TeamB
Randy,Rhodes,randy@rock.io,manager,TeamB
Eric,Clapton,eric@rock.io,manager
```

Script no longer uses the python SDK, but rather calls the API endpoints directly.

**Comment by toddm92** [comment]
Closing...
