### ISSUE TITLE
Script to lock down SGs in response to any ESP SG ingress signature

### ISSUE THREAD

**Issue by jhubbardevident** [EvidentSecurity/automation#5]
### ESP Automation Request

---
Prospect is requesting and automation script to revoke global ingress SG rules WITHOUT the use of custom signatures. The custom signature engine runs hourly and therefore built-in signatures are preferred. 

Currently, the way to do this would be 1 lambda function that responds to EC2-007, EC2-040, and the all of the specific admin port signatures. This will cover the complete port range from 0-65535. 

#### Request (Select one):

- [x] Automation Script
- [ ] Auto-Remediation Function

#### Type (Select one):

- [x] New Project
- [ ] Feature Enhancement
- [ ] Bug Report

#### Priority:

- [X] High
- [] Medium
- [ ] Low
 
 
#### Cloud Provider:

- [x] AWS
- [ ] Azure

#### Description:

[ If the current behavior is a bug, please provide the steps to reproduce. ]

#### Use Case:

[ What is the expected behavior? ]
If an global (0.0.0.0/0,::/0) ingress rule is detected from the signatures listed above, revoke the rule from the security group. The activity should be logged to CWL.

#### Technical Requirements:

[ Provide details. ]
python 2.7 lambda function

#### Supporting Image / Examples:

```
Code examples, error output, etc.
```
IF security group rule is flagged from 1 of the signatures above, execute lambda function
Scan security group rules for global ingress rules
If global ingress rule exists, revoke rule
      log if error revoking rule
else
      log if no rules exists that need to be revoked

#### Additional Comments:

Reach out to me for information on prospect as these issues are public

**Comment by toddm92** [comment]
@jhubbardevident I've ran this script through a couple test scenarios.. seems to be working as expected.

* lambda script: ```AWS_EC2_security_group_lock_down.py```

use can use the following policy with it: ```AWS_EC2_security_group_global_inbound_policy.json```

It will remediate the following built-in signatures:

* EC2-009 MySQL (TCP Port 3306) Detected
* EC2-010 PostgreSQL (TCP Port 5432) Detected
* EC2-011 SQLServer (TCP Port 1433) Detected
* EC2-012 SQLServer (UDP Port 1434) Detected
* EC2-013 MSQL (TCP Port 4333) Detected
* EC2-014 VNC Listener (TCP Port 5500) Detected
* EC2-015 VNC Server (TCP Port 5900) Detected
* EC2-016 NetBIOS (UDP Port 137) Detected
* EC2-017 NetBIOS (UDP Port 138) Detected
* EC2-018 CIFS (UDP Port 445) Detected
* EC2-019 FTP (TCP Port 21) Detected
* EC2-020 FTP-Data (TCP Port 20) Detected
* EC2-021 SMTP (TCP Port 25) Detected
* EC2-022 (Ping) Access Detected
* EC2-023 DNS (UDP Port 53) Detected
* EC2-024 DNS (TCP Port 53) Detected
* EC2-040 Global permission is defined on a range of ports

lemme know if this is what you had in mind...
