### ISSUE TITLE
Snapshot ec2 instances in non-primary regions and terminate

### ISSUE THREAD

**Issue by brandenlundy** [EvidentSecurity/automation#6]
### ESP Automation Request

We are looking for a script that will automatically take a snapshot of ec2 instances in non-primary regions and then terminate those ec2 instances. This is something that we want to use internally and is a request from Rick. 

---

#### Request (Select one):

- [x] Automation Script
- [ ] Auto-Remediation Function

#### Type (Select one):

- [x] New Project
- [ ] Feature Enhancement
- [ ] Bug Report

#### Priority:

- [ ] High
- [x] Medium
- [ ] Low
 
 
#### Cloud Provider:

- [x] AWS
- [ ] Azure

#### Description:

[ If the current behavior is a bug, please provide the steps to reproduce. ]

#### Use Case:

[ What is the expected behavior? ]

We want to use this internally on our own accounts. 

#### Technical Requirements:

Snapshot unnecessary ec2 instances and terminate them after the snapshot has completed. 

#### Supporting Image / Examples:

```
Code examples, error output, etc.
```

#### Additional Comments:

[ The customer would like XYZ... ]

**Comment by toddm92** [comment]
@brandenlundy First version of a script has been pushed to the repo...

script name: ``` instances_nonpri_regions.py ```

#### Description
This script will take a snapshot (image) of ec2 instances in non-primary regions then attempt to terminate those ec2 instances.

#### Requirements
* python v3
* boto3
* valid AWS config/profile -> ~/.aws/credentials

#### AWS permissions
* ec2.describe_instances
* ec2.describe_images
* ec2.create_image
* ec2.terminate_instances

The script is designed to be run on it's own or from cron.  When we have a corresponding signature, we can make it "lambda friendly."  Another idea is to run the script from AWS Config as a rule.  Unfortunately, I think we'd have to create a Rule in each non-primary region.

**Comment by brandenlundy** [comment]
I dont think this will work. Tim/Justin wanted us to use some lambda
autoremeditate function or functions internally so we could tell customers
that we are doing that
and Rick was the one who specified what he wanted the autoremeditate
function to do. Do I need to talk to someone else about developing a custom
signature for this?

**Comment by toddm92** [comment]
@brandenlundy ok - I was guided by the description in the issue which stated...

*"We are looking for a script that will automatically take a snapshot of ec2 instances in non-primary regions and then terminate those ec2 instances. This is something that we want to use internally and is a request from Rick."*

We can certainly develop a custom signature.  And we can easily turn the script into a lambda function.

Can you provide the requirements for the signature and submit an issue?  I'm guessing the signature would be triggered by ANY ec2 instance in a running/stopped state in a non-primary region?

**Comment by brandenlundy** [comment]
Yes that is the idea. I apologize for not being more clear in writing the
ticket. They are wanting a lambda function to say we are doing serverless
autoremediation internally.

**Comment by toddm92** [comment]
@brandenlundy no worries.  I'll jump on this next week.  Thx.

**Comment by toddm92** [comment]
@brandenlundy 

Ok, custom signature is located here:
https://github.com/EvidentSecurity/custom_signatures/blob/master/AWS_EC2%20-%20instances_nonpri_regions.rb

Auto remediation function is located here:
https://github.com/EvidentSecurity/automation/blob/master/autoremediate/aws/lambda/AWS_EC2_instances_nonpri_regions_remediate.py

Lambda policy:
https://github.com/EvidentSecurity/automation/blob/master/autoremediate/aws/policies/AWS_EC2_instances_nonpri_regions_policy.json

Your lambda settings should be:
* 128 memory
* 5 minute timeout (the max)

We're using a wait condition in the lambda function.  It waits until the new machine image (AMI) is available before terminating the instance.  If however, the image takes longer than 5 minutes to create and become available, there's a chance lambda will timeout before terminating the instance.  I've tested about a dozen different times and ran into this scenario only once.

If it becomes an issue for you, we can look into possibly modifying the wait condition.

**Comment by toddm92** [comment]
Instructions / walkthrough located here...
https://github.com/EvidentSecurity/automation/blob/master/autoremediate/aws/docs/instances_nonpri_regions.md

**Comment by brandenlundy** [comment]
Thanks a ton for this! I really appreciate the instructions.
